import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./Sidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //find active route and highlight it in the navigation bar


  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-slate-50!">
        <div className="flex min-h-full h-full w-full flex-col bg-slate-50 ">
          <div className="max-w-6xl! w-full mx-auto space-y-6 py-">
            {/* HEADER */}
            <header className="flex flex-wrap py-4 items-center justify-between gap-3">
              <div>
                <h1 className="text-2xl font-bold tracking-tight text-slate-900">
                  Office Power Dashboard
                </h1>
                <p className="text-sm text-slate-500">
                  Live fan & light telemetry across all rooms.
                </p>
              </div>
            </header>
            <Sidebar />

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
          
       